name: 'Generate documentation with Doxygen'

on:
  push:
    branches:
      - dev
    tags:
      - '*'

env:
  TARGETS: f7 f18
  DEFAULT_TARGET: f7

jobs:
  doxygen:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Wipe workspace'
        run: find ./ -mount -maxdepth 1 -exec rm -rf {} \;

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: 'Get commit details'
        id: names
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
          else
            TYPE="other"
          fi
          python3 scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE"

      - name: 'Install requirements'
        run: |
          sudo apt install -y doxygen
          sudo python3 -m pip install sphinx sphinx_rtd_theme doxysphinx sphinx-multiversion myst-parser
